name: CI
run-name: ${{ github.actor}} run github actions

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Say hello world to the everybody
        run: echo "Hello world!!!"
        
      - name: work with secrets
        env:
          NAME: "${{ secrets.MYNAME }}"
        run: echo "My secret is ${NAME}"
        

  build2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Say hello world to the everybody
        run: echo "Hello world!!!"

  build3:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest]
        python-versions: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-versions }}
        uses: actions/setup-python@v4
        with:
          python-versions: ${{ matrix.python-versions }}

    