name: CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Say hello world to the everybody
        run: echo "Hello world!!!"

  build2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Say hello world to the everybody
        run: echo "Hello world!!!"