name: CI
run-name: ${{ github.actor}} run github actions

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Say hello world to the everybody
        run: echo "Hello world!!!"
        
      - name: work with secrets
        env:
          NAME: "${{ MYNAME }}"
        run: echo "My secret is ${NAME}"
        

  build2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Say hello world to the everybody
        run: echo "Hello world!!!"